#!/usr/bin/env bash
# Build seerr-windows-setup.exe (NSIS) from a portable folder.
# Installs to %LOCALAPPDATA%\Programs\Seerr so the folder stays user-writable
# and in-app auto-update (robocopy apply script) works without elevation.
#
# Usage: packaging/make-windows-setup.sh <portable-dir> <out-setup.exe> [version]
set -euo pipefail

PORTABLE="${1:?portable directory (e.g. build/seerr-portable)}"
OUT_EXE="${2:?output setup.exe path}"
VER="${3:-0.1.0}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [[ ! -d "$PORTABLE" ]]; then
  echo "missing portable dir: $PORTABLE" >&2
  exit 1
fi
if [[ ! -f "$PORTABLE/seerr.exe" ]]; then
  echo "missing seerr.exe in $PORTABLE" >&2
  exit 1
fi
if ! command -v makensis >/dev/null 2>&1; then
  echo "error: makensis not found - install mingw-w64-x86_64-nsis (MSYS2)" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT_EXE")"
NSI_DIR="${ROOT}/build/nsis-work"
rm -rf "$NSI_DIR"
mkdir -p "$NSI_DIR"

# NSIS needs Windows-style paths
to_win() {
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -w "$1"
  else
    # Best-effort: forward → backslash
    echo "$1" | sed 's|/|\\|g'
  fi
}

PORTABLE_WIN="$(to_win "$(cd "$PORTABLE" && pwd)")"
OUT_WIN="$(to_win "$(cd "$(dirname "$OUT_EXE")" && pwd)/$(basename "$OUT_EXE")")"
NSI="$NSI_DIR/seerr-setup.nsi"

# Escape backslashes for NSIS string literals
esc_nsis() { printf '%s' "$1" | sed 's|\\|\\\\|g'; }

# Numeric ProductVersion for Windows (X.Y.Z.W)
NUM_VER="$(echo "$VER" | sed -E 's/[^0-9.].*$//; s/^\.+//; s/\.+$//')"
[[ -z "$NUM_VER" ]] && NUM_VER="0.1.0"
V1="$(echo "$NUM_VER" | cut -d. -f1)"; V1="${V1:-0}"
V2="$(echo "$NUM_VER" | cut -d. -f2)"; V2="${V2:-0}"
V3="$(echo "$NUM_VER" | cut -d. -f3)"; V3="${V3:-0}"
V4="$(echo "$NUM_VER" | cut -d. -f4)"; V4="${V4:-0}"
# Ensure purely numeric components
V1="$(echo "$V1" | tr -cd '0-9')"; V1="${V1:-0}"
V2="$(echo "$V2" | tr -cd '0-9')"; V2="${V2:-0}"
V3="$(echo "$V3" | tr -cd '0-9')"; V3="${V3:-0}"
V4="$(echo "$V4" | tr -cd '0-9')"; V4="${V4:-0}"
PRODUCT_VERSION="${V1}.${V2}.${V3}.${V4}"

# Installer + shortcut icon (committed ICO - no ImageMagick required in CI).
ICON_PNG="${ROOT}/vendor/icon.png"
ICON_ICO_SRC="${ROOT}/vendor/seerr.ico"
ICON_ICO="$NSI_DIR/seerr.ico"
ICON_LINE=""
if [[ -f "$ICON_ICO_SRC" ]]; then
  cp -f "$ICON_ICO_SRC" "$ICON_ICO"
elif [[ -f "$ICON_PNG" ]] && command -v magick >/dev/null 2>&1; then
  magick "$ICON_PNG" -define icon:auto-resize=256,128,64,48,32,16 "$ICON_ICO" 2>/dev/null || true
fi
if [[ -f "$ICON_ICO" ]]; then
  ICON_WIN="$(to_win "$ICON_ICO")"
  ICON_ESC="$(esc_nsis "$ICON_WIN")"
  ICON_LINE="!define MUI_ICON \"$ICON_ESC\"
!define MUI_UNICON \"$ICON_ESC\""
fi

PORTABLE_ESC="$(esc_nsis "$PORTABLE_WIN")"
OUT_ESC="$(esc_nsis "$OUT_WIN")"

cat > "$NSI" <<EOF
; Generated by packaging/make-windows-setup.sh - do not edit by hand.
Unicode true
CRCCheck on
SetCompressor /SOLID lzma
RequestExecutionLevel user

!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"

Name "Seerr"
OutFile "$OUT_ESC"
InstallDir "\$LOCALAPPDATA\\Programs\\Seerr"
InstallDirRegKey HKCU "Software\\Seerr" "InstallDir"
ShowInstDetails show
ShowUnInstDetails show

VIProductVersion "${PRODUCT_VERSION}"
VIAddVersionKey "ProductName" "Seerr"
VIAddVersionKey "FileDescription" "Seerr Setup"
VIAddVersionKey "FileVersion" "${VER}"
VIAddVersionKey "ProductVersion" "${VER}"
VIAddVersionKey "LegalCopyright" "Seerr"

${ICON_LINE}
!define MUI_ABORTWARNING
!define MUI_FINISHPAGE_RUN "\$INSTDIR\\seerr.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch Seerr"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Polish"

Section "Seerr" SecApp
  SectionIn RO
  SetOutPath "\$INSTDIR"
  ; Full portable tree (exe + MinGW DLLs + libvlc + assets)
  File /r "${PORTABLE_ESC}\\*.*"

  ; Start Menu - icon from embedded exe resource (and seerr.ico beside it)
  CreateDirectory "\$SMPROGRAMS\\Seerr"
  CreateShortCut "\$SMPROGRAMS\\Seerr\\Seerr.lnk" "\$INSTDIR\\seerr.exe" "" "\$INSTDIR\\seerr.exe" 0
  CreateShortCut "\$SMPROGRAMS\\Seerr\\Uninstall Seerr.lnk" "\$INSTDIR\\Uninstall.exe"

  ; Registry (per-user) - keeps install path writable for auto-update
  WriteRegStr HKCU "Software\\Seerr" "InstallDir" "\$INSTDIR"
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr" "DisplayName" "Seerr"
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr" "DisplayVersion" "${VER}"
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr" "Publisher" "Seerr"
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr" "InstallLocation" "\$INSTDIR"
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr" "UninstallString" '"\$INSTDIR\\Uninstall.exe"'
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr" "QuietUninstallString" '"\$INSTDIR\\Uninstall.exe" /S'
  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr" "DisplayIcon" "\$INSTDIR\\seerr.exe,0"
  WriteRegDWORD HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr" "NoModify" 1
  WriteRegDWORD HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr" "NoRepair" 1
  \${GetSize} "\$INSTDIR" "/S=0K" \$0 \$1 \$2
  IntFmt \$0 "0x%08X" \$0
  WriteRegDWORD HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr" "EstimatedSize" "\$0"

  WriteUninstaller "\$INSTDIR\\Uninstall.exe"
SectionEnd

Section "Uninstall"
  Delete "\$SMPROGRAMS\\Seerr\\Seerr.lnk"
  Delete "\$SMPROGRAMS\\Seerr\\Uninstall Seerr.lnk"
  RMDir "\$SMPROGRAMS\\Seerr"

  DeleteRegKey HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Seerr"
  DeleteRegKey HKCU "Software\\Seerr"

  ; Remove install tree (Uninstall.exe last)
  RMDir /r "\$INSTDIR"
SectionEnd
EOF

echo "Building NSIS installer…"
echo "  portable: $PORTABLE"
echo "  output:   $OUT_EXE"
echo "  version:  $VER (ProductVersion $PRODUCT_VERSION)"
makensis -V2 "$NSI"

if [[ ! -f "$OUT_EXE" ]]; then
  # makensis writes to OutFile; if path translation failed, look for adjacent default
  echo "error: setup.exe not produced at $OUT_EXE" >&2
  exit 1
fi

ls -lah "$OUT_EXE"
echo "Windows setup ready: $OUT_EXE"
echo "  Installs to %LOCALAPPDATA%\\Programs\\Seerr (user-writable → auto-update OK)"
