# Boost + libtorrent resolution (system or FetchContent).

include(FetchContent)

function(seerr_ensure_boost_headers)
    if(TARGET Boost::headers)
        return()
    endif()
    add_library(seerr_boost_headers INTERFACE)
    add_library(Boost::headers ALIAS seerr_boost_headers)
    if(DEFINED Boost_INCLUDE_DIRS AND NOT "${Boost_INCLUDE_DIRS}" STREQUAL "")
        target_include_directories(seerr_boost_headers INTERFACE ${Boost_INCLUDE_DIRS})
    elseif(DEFINED Boost_INCLUDE_DIR AND NOT "${Boost_INCLUDE_DIR}" STREQUAL "")
        target_include_directories(seerr_boost_headers INTERFACE ${Boost_INCLUDE_DIR})
    endif()
endfunction()

if(SEERR_BUNDLED_DEPS)
    FetchContent_Declare(
        boost_src
        URL https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.gz
        DOWNLOAD_EXTRACT_TIMESTAMP TRUE
    )
    FetchContent_GetProperties(boost_src)
    if(NOT boost_src_POPULATED)
        FetchContent_Populate(boost_src)
    endif()

    set(BOOST_ROOT "${boost_src_SOURCE_DIR}" CACHE PATH "" FORCE)
    set(Boost_INCLUDE_DIR "${boost_src_SOURCE_DIR}" CACHE PATH "" FORCE)
    set(Boost_NO_SYSTEM_PATHS ON)
    set(Boost_NO_BOOST_CMAKE ON)
    find_package(Boost 1.70 REQUIRED)
    seerr_ensure_boost_headers()

    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
    set(deprecated-functions OFF CACHE BOOL "" FORCE)
    set(encryption OFF CACHE BOOL "" FORCE)
    set(build_tests OFF CACHE BOOL "" FORCE)
    set(build_examples OFF CACHE BOOL "" FORCE)
    set(build_tools OFF CACHE BOOL "" FORCE)
    set(python-bindings OFF CACHE BOOL "" FORCE)

    FetchContent_Declare(
        libtorrent
        GIT_REPOSITORY https://github.com/arvidn/libtorrent.git
        GIT_TAG        v2.0.11
        GIT_SHALLOW    TRUE
    )
    FetchContent_MakeAvailable(libtorrent)
    set(SEERR_TORRENT_TARGET torrent-rasterbar)
else()
    # Try Config package first (modern distros), then module mode.
    find_package(Boost 1.70 QUIET CONFIG)
    if(NOT Boost_FOUND)
        find_package(Boost 1.70 REQUIRED)
    endif()
    seerr_ensure_boost_headers()

    find_package(PkgConfig QUIET)
    set(SEERR_TORRENT_TARGET "")
    if(PkgConfig_FOUND)
        pkg_check_modules(LIBTORRENT libtorrent-rasterbar)
        if(LIBTORRENT_FOUND)
            # MSYS2 pkg-config emits /mingw64/... which CMake on Windows cannot use as-is.
            set(_msys_prefix "")
            if(DEFINED ENV{MSYSTEM_PREFIX} AND NOT "$ENV{MSYSTEM_PREFIX}" STREQUAL "")
                set(_msys_prefix "$ENV{MSYSTEM_PREFIX}")
            elseif(EXISTS "C:/msys64/mingw64")
                set(_msys_prefix "C:/msys64/mingw64")
            endif()
            if(_msys_prefix)
                foreach(_var LIBTORRENT_INCLUDE_DIRS LIBTORRENT_LIBRARY_DIRS)
                    set(_fixed "")
                    foreach(_p IN LISTS ${_var})
                        if(_p MATCHES "^/mingw64")
                            string(REGEX REPLACE "^/mingw64" "${_msys_prefix}" _p "${_p}")
                        endif()
                        list(APPEND _fixed "${_p}")
                    endforeach()
                    set(${_var} "${_fixed}")
                endforeach()
                set(_fixed "")
                foreach(_p IN LISTS LIBTORRENT_LDFLAGS)
                    if(_p MATCHES "^-L/mingw64")
                        string(REGEX REPLACE "^-L/mingw64" "-L${_msys_prefix}" _p "${_p}")
                    elseif(_p MATCHES "^/mingw64")
                        string(REGEX REPLACE "^/mingw64" "${_msys_prefix}" _p "${_p}")
                    endif()
                    list(APPEND _fixed "${_p}")
                endforeach()
                set(LIBTORRENT_LDFLAGS "${_fixed}")
            endif()
            if(LIBTORRENT_LIBRARY_DIRS)
                list(REMOVE_DUPLICATES LIBTORRENT_LIBRARY_DIRS)
            endif()
            if(LIBTORRENT_INCLUDE_DIRS)
                list(REMOVE_DUPLICATES LIBTORRENT_INCLUDE_DIRS)
            endif()
            # Drop "-isystem <mingw prefix>/include" — breaks #include_next <stdlib.h>.
            set(_lt_cflags "")
            set(_lt_drop_next FALSE)
            foreach(_lt_flag IN LISTS LIBTORRENT_CFLAGS_OTHER)
                if(_lt_drop_next)
                    set(_lt_drop_next FALSE)
                    continue()
                endif()
                if(_lt_flag STREQUAL "-isystem")
                    set(_lt_drop_next TRUE)
                    continue()
                endif()
                string(FIND "${_lt_flag}" "-isystem" _lt_pos)
                if(_lt_pos EQUAL 0)
                    continue()
                endif()
                list(APPEND _lt_cflags "${_lt_flag}")
            endforeach()
            set(LIBTORRENT_CFLAGS_OTHER "${_lt_cflags}")
            add_library(seerr_libtorrent INTERFACE)
            target_include_directories(seerr_libtorrent INTERFACE ${LIBTORRENT_INCLUDE_DIRS})
            target_link_directories(seerr_libtorrent INTERFACE ${LIBTORRENT_LIBRARY_DIRS})
            target_link_libraries(seerr_libtorrent INTERFACE ${LIBTORRENT_LIBRARIES})
            target_compile_options(seerr_libtorrent INTERFACE ${LIBTORRENT_CFLAGS_OTHER})
            set(SEERR_TORRENT_TARGET seerr_libtorrent)
        endif()
    endif()
    if(SEERR_TORRENT_TARGET STREQUAL "")
        find_package(LibtorrentRasterbar QUIET)
        if(TARGET LibtorrentRasterbar::torrent-rasterbar)
            set(SEERR_TORRENT_TARGET LibtorrentRasterbar::torrent-rasterbar)
        elseif(TARGET torrent-rasterbar)
            set(SEERR_TORRENT_TARGET torrent-rasterbar)
        else()
            message(FATAL_ERROR
                "libtorrent-rasterbar not found.\n"
                "  Debian/Ubuntu: sudo apt install libtorrent-rasterbar-dev libboost-dev\n"
                "  Or: cmake -DSEERR_BUNDLED_DEPS=ON …")
        endif()
    endif()
endif()

message(STATUS "Seerr torrent target: ${SEERR_TORRENT_TARGET}")
message(STATUS "Seerr bundled deps: ${SEERR_BUNDLED_DEPS}")
